on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: cloud-linux104.thaidatahosting.com
        username: zhaiii@chiwamitra.com
        password: Admin@123
        protocol: ftp
        port: 2121 
        local-dir: ./dist/
        server-dir: domains/125street.net/public_html/test